name: Sleep App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Create google-services.json
      run: |
        echo '${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}' > app/google-services.json
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Check & Test
      run: ./gradlew check test
    - name: Upload test report artifact
      #if: ${{ failure() }}
      uses: actions/upload-artifact@v3
      with:
        name: sleep-app-test-report
        path: /home/runner/work/sleep/sleep/app/build/reports/lint-results-debug.html
