name: Deploy on Play Store

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Create google-services.json
      run: |
        echo '${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}' > app/google-services.json
    - name: Run tests 
      run: ./gradlew testRelease
      
  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Create keystore
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" > release.keystore.asc
        gpg -d --passphrase "${{ secrets.RELEASE_KEYSTORE_PASSPHRASE }}" --batch release.keystore.asc > app/release.keystore
    - name: Create google-services.json
      run: |
        echo '${{ secrets.FIREBASE_GOOGLE_SERVICES_JSON }}' > app/google-services.json
    - name: Build release
      run: ./gradlew bundleRelease
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: aab
        path: ./app/build/outputs/bundle/release/app-release.aab

  publish:
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: aab
    - name: Publish on Google Play Store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: dev.marcocattaneo.sleep
        releaseFiles: app-release.aab
